### ISSUE TITLE
Doesn't work on 10.11.2

### ISSUE THREAD

**Issue by RSully** [aburgh/Disk-Arbitrator#14]
I compiled 0.5.0 and set it to read-only mode. Volume mounted normally (i.e. NOT read only). When I unmounted and manually mounted it was read only. At the very least this resulted in changes to `.DS_Store` among other hidden files in the root.

**Comment by kainjow** [comment]
Sorry for the delay. I was able to reproduce with 10.11.4, seems somehow as it's ignoring the mount arg "rdonly". Looking into it...

**Comment by kainjow** [comment]
This should be fixed now. I'm not sure what the issue was, but since the DiskArbitration framework is poorly documented, there may have been assumptions used in Disk Arbitrator that are no longer true in El Capitan (or a previous version of OS X).

The program would attempt to re-mount a disk as read only when the disk first is made visible to the operating system, but due to the DiskArb API it's impossible (based on my knowledge) to know when a disk is being mounted as read only. All we can get is the notification that it's being mounted. So my fix was to only mount disks when we've first rejected the original mount request, so that we get a basic assurance that the next mount request is coming from us, where we specified that we want to mount it as read only.

Apple could improve this by allowing the API to report the mount arguments, and/or allowing the mount command to provide arbitrary data, so then we can properly determine where the mount is coming from. Until then, this workaround seems to resolve the problem.

Please test if you can, otherwise I'll make a new official build.

**Comment by kainjow** [comment]
0.6 has been released to address this issue.
